# Generated by Django 6.0.1 on 2026-02-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='manager',
        ),
    ]
