# Generated by Django 6.0.1 on 2026-02-11 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='hotel.servicebooking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='hotel.reservation'),
        ),
    ]
